# Generated by Django 3.1.2 on 2020-10-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0025_auto_20190711_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=250, null=True)),
                ('sid', models.CharField(db_index=True, max_length=250, null=True, unique=True)),
                ('agent', models.CharField(db_index=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
